async function Module(moduleArg={}){var Module=moduleArg;var h=!!globalThis.WorkerGlobalScope,k="./this.program",aa=import.meta.url,l="",n,p;if(globalThis.window||h){try{l=(new URL(".",aa)).href}catch{}h&&(p=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});n=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var q=console.log.bind(console),t=console.error.bind(console),u=!1,w,x=!1;function z(){if(!A?.buffer?.C){a:{try{var a=
B.toResizableBuffer();break a}catch{}a=B.buffer}A=new Int8Array(a);new Int16Array(a);Module.HEAPU8=C=new Uint8Array(a);new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);new Float32Array(a);Module.HEAPF64=new Float64Array(a);F=new BigInt64Array(a);new BigUint64Array(a)}}function ba(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),H.push(...a));for(a=H;a.length>0;)a.shift()(Module)}function ca(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),I.push(...a));for(a=I;a.length>0;)a.shift()(Module)}
function J(a){Module.onAbort?.(a);a=`Aborted(${a})`;t(a);u=!0;a+=". Build with -sASSERTIONS for more info.";x&&K();throw new WebAssembly.RuntimeError(a);}var L;async function da(a){try{var b=await n(a);return new Uint8Array(b)}catch{}if(p)a=p(a);else throw"both async and sync fetching of the wasm failed";return a}async function ea(a,b){try{var c=await da(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),J(d)}}async function fa(a){var b=L;try{var c=
fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return ea(b,a)}class M{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var D,F,A,E,C,I=[],H=[],N=!0,O=0,ha=[0,31,60,91,121,152,182,213,244,274,305,335],ia=[0,31,59,90,120,151,181,212,243,273,304,334],P={},Q=a=>{if(!(a instanceof M||a=="unwind"))throw a;},R=a=>{w=a;N||
O>0||(Module.onExit?.(a),u=!0);throw new M(a);},ja=a=>{if(!u)try{a()}catch(b){Q(b)}finally{if(!(N||O>0))try{w=a=w,R(a)}catch(b){Q(b)}}},S=(a,b,c)=>{var d=C;if(!(c>0))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(f<=127){if(b>=c)break;d[b++]=f}else if(f<=2047){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(f<=65535){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&
63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},T={},V=()=>{if(!U){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:k},b;for(b in T)T[b]===void 0?delete a[b]:a[b]=T[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);U=c}return U},U,W=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},ka=[null,[],[]],X=new TextDecoder,la=(a,b,c,d)=>
{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},ma=()=>a=>(crypto.getRandomValues(a),0),na=a=>(na=ma())(a);Module.noExitRuntime&&(N=Module.noExitRuntime);Module.print&&(q=Module.print);Module.printErr&&(t=Module.printErr);Module.thisProgram&&(k=Module.thisProgram);var Y=Module.preInit;if(Y)for(typeof Y=="function"&&(Module.preInit=Y=[Y]);Y.length>0;)Y.shift()();Module.UTF8ToString=(a,b,c)=>a?X.decode(C.subarray(a,la(C,a,b,c))):"";Module.stringToUTF8=(a,b,c)=>S(a,b,c);Module.lengthBytesUTF8=
W;var oa,K,B,pa={l:()=>{},k:()=>{},g:()=>J(""),f:()=>{N=!1;O=0},h:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;D[b>>2]=a.getSeconds();D[b+4>>2]=a.getMinutes();D[b+8>>2]=a.getHours();D[b+12>>2]=a.getDate();D[b+16>>2]=a.getMonth();D[b+20>>2]=a.getFullYear()-1900;D[b+24>>2]=a.getDay();var c=a.getFullYear();D[b+28>>2]=(c%4!==0||c%100===0&&c%400!==0?ia:ha)[a.getMonth()]+a.getDate()-1|0;D[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();D[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;return 0},i:(a,b)=>{P[a]&&(clearTimeout(P[a].id),delete P[a]);if(!b)return 0;var c=setTimeout(()=>{delete P[a];ja(()=>oa(a,performance.now()))},b);P[a]={id:c,D:b};return 0},q:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=Math.max(g,e)*60;D[b>>2]=Number(g!=e);b=f=>{var v=Math.abs(f);
return`UTC${f>=0?"-":"+"}${String(Math.floor(v/60)).padStart(2,"0")}${String(v%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(S(a,c,17),S(b,d,17)):(S(a,d,17),S(b,c,17))},d:function(a,b,c){if(!(a>=0&&a<=3))return 28;F[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},c:a=>{var b=C.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-B.buffer.byteLength+65535)/
65536|0;try{B.grow(d);z();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},m:(a,b)=>{var c=0,d=0,e;for(e of V()){var g=b+c;E[a+d>>2]=g;c+=S(e,g,Infinity)+1;d+=4}return 0},n:(a,b)=>{var c=V();E[a>>2]=c.length;a=0;for(var d of c)a+=W(d)+1;E[b>>2]=a;return 0},o:()=>52,b:()=>52,p:function(){return 70},a:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=E[b>>2],v=E[b+4>>2];b+=8;for(var G=0;G<v;G++){var y=a,m=C[f+G],r=ka[y];m===0||m===10?(y=y===1?q:t,m=la(r,0),m=X.decode(r.buffer?r.subarray(0,m):new Uint8Array(r.slice(0,
m))),y(m),r.length=0):r.push(m)}e+=v}E[d>>2]=e;return 0},r:function(a,b){for(var c="";C[b];++b)c+=String.fromCharCode(C[b]);if(Module.onLog)Module.onLog(a,c);else a===1?console.warn(c):console.log(c)},e:R,j:(a,b)=>na(C.subarray(a,a+b))},Z;Z=await (async function(){function a(d){d=Z=d.exports;Module._pxDeltaGamma_impVol=d.u;Module._ql_wasm_build_date=d.v;Module._ql_wasm_expiry_date=d.w;Module._ql_wasm_set_today=d.x;oa=d.y;Module._free=d.z;Module._malloc=d.A;K=d.B;B=d.s;z();return Z}var b=
{a:pa},c=Module.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});L??=Module.locateFile?Module.locateFile?Module.locateFile("cvtbond.wasm",l):l+"cvtbond.wasm":(new URL("cvtbond.wasm",import.meta.url)).href;return function(d){return a(d.instance)}(await fa(b))}());await (async function(){ba();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));u||(x=!0,Z.t(),Module.onRuntimeInitialized?.(),ca())}());;return Module}export default Module;
